<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <div>
        <?php echo $this->getChildHtml('head'); ?>
    </div>
</head>

<body>
    <div>
        <?php echo $this->getChildHtml('header'); ?>
    </div>
    <div>
        <?php echo $this->getChildHtml('messages'); ?>
    </div>
    <div class='contentPage'>
        <?php echo $this->getChildHtml('content'); ?>
    </div>
    <div>
        <?php echo $this->getChildHtml('footer'); ?>
    </div>
</body>

</html>