<?php $itemData = $this->getItemData();
$quoteId = $this->getItemData()->getFirstItem();
$totalItem = 0;
$totalQty = 0;
?>

<div class="cart-container">
    <h1>Your Shopping Cart</h1>
    <div class="cart-items">

        <?php foreach ($itemData->getData() as $item): ?>
        <div class="cart-item">
            <img src="<?php echo Mage::getBaseUrl('media/product/') . $this->getProduct($item->getProductId())->getImageLink() ?>"
                alt="Product 1">
            <div class="item-details">
                <h3>
                    <?php echo $this->getProduct($item->getProductId())->getName() ?>
                </h3>
                <p>Price:
                    <?php echo $item->getPrice(); ?>
                </p>
                <div class="quantity-section">
                    <form action="<?php echo Mage::getBaseUrl('sales/quote/update') ?>" method="post">
                        <input type="hidden" name="item_id" value="<?php echo $item->getItemId(); ?>">
                        <label for="new_qty">Quantity:</label>
                        <input type="number" name="new_qty" value="<?php echo $item->getQty() ?>" min="1">
                        <input type="submit" value="Update" class="update-btn">
                    </form>
                </div>
                <p>Total Cost: $
                    <?php echo $item->getQty() * $item->getPrice(); ?>
                </p>
                <button class="remove-item" onclick="removeItem(<?php echo $item->getProductId(); ?>)"><a
                        href="<?php echo Mage::getBaseUrl('sales/quote/delete?id=' . $item->getItemId()) ?>">Remove</a></button>
            </div>
        </div>
        <?php $totalItem++;
            $totalQty += $item->getQty(); ?>
        <?php endforeach; ?>

    </div>
    <hr>
    <div class="cart-summary">
        <p>Total Items: <span id="total-items">
                <?php echo $totalItem ?>
            </span></p>
        <p>Total Quantity: <span id="total-quantity">
                <?php echo $totalQty ?>
            </span></p>
        <p>Total Price: $<span id="total-price">
                <?php echo $this->getQuoteData($quoteId->getQuoteId())->getGrandTotal(); ?>
            </span></p>
        <form action="<?php echo Mage::getBaseUrl('cart/checkout/checkout') ?>" method="post">
            <button class="checkout-btn">Checkout</button>
        </form>
    </div>
</div>