<?php

echo $this->getRequest()->getParams('pid');
$productModel = Mage::getModel('catalog/product')->load(2);
// $formObj = Mage::getBlock('catalog/admin_product');
//print_r($productModel->load(2));
// print_r($formObj);
// $formObj->toHtml();
// Mage::getBlock('catalog/admin_product')->toHtml();
// echo "<pre>";
// print_r($productModel);
// print_r($productModel->getId());
// print_r($productModel->getProductName());
// print_r($productModel->getSku());
echo $this->getChildHtml('');