<header>

    <nav class="navbar">
        <div class="header-title">
            <a href="<?php echo Mage::getBaseUrl(); ?>" class="logo"><img
                    src="<?php echo Mage::getBaseUrl('skin/images/icon.png') ?>" alt="Logo" id="img1"></a>
            <h1><a href="<?php echo Mage::getBaseUrl(); ?>">CyberCom-Creation</a></h1>
        </div>
        <div class="container">

            <ul class="menu">
                <li><a href="<?php echo Mage::getBaseUrl(); ?>">Home</a></li>
                <li><a href="<?php echo Mage::getBaseUrl('admin/user/login'); ?>">Admin Login</a></li>
                <li><a href="<?php echo Mage::getBaseUrl('customer/account/login'); ?>">Customer Login</a></li>
                <li><a href="<?php echo Mage::getBaseUrl('customer/account/Dashboard'); ?>">Dashboard</a></li>
                <li><a href="<?php echo Mage::getBaseUrl('admin/catalog_product/form'); ?>">Product Form</a></li>

            </ul>
        </div>
    </nav>
</header>