<header>
    <?php $categories = $this->getCategory(); ?>
    <nav class="navbar">
        <div class="header-title">
            <a href="<?php echo Mage::getBaseUrl(); ?>" class="logo"><img
                    src="<?php echo Mage::getBaseUrl('skin/images/logo.png') ?>" alt="Logo" id="img1"></a>
            <h1><a href="<?php echo Mage::getBaseUrl(); ?>">CyberCom-Creation</a></h1>
        </div>
        <div class="container">

            <ul class="menu">
                <li><a href="<?php echo Mage::getBaseUrl(); ?>">Home</a></li>
                <li><a href="<?php echo Mage::getBaseUrl('customer/account/login'); ?>">Customer Login</a></li>
                <li><a href="<?php echo Mage::getBaseUrl('customer/account/Dashboard'); ?>">Dashboard</a></li>
                <li class="dropdown">
                    <a href="<?php echo Mage::getBaseUrl('catalog/category/view'); ?>">Categories</a>
                    <ul class="category-dropdown">
                        <?php
                        foreach ($categories->getData() as $category) {
                            $categoryName = $category->getCategoryName();
                            $categoryId = $category->getCategoryId();
                            $link = Mage::getBaseUrl('catalog/category/view?id=') . $categoryId;
                            echo "<li><a href='$link'>$categoryName</a></li>";
                        }
                        ?>
                    </ul>
                </li>
                <li><a href="<?php echo Mage::getBaseUrl('cart/index/view'); ?>">Cart</a></li>
                <li><a href="<?php echo Mage::getBaseUrl('admin/user/login'); ?>">Admin Login</a></li>
            </ul>
        </div>
    </nav>
</header>