<div class="card">
    <h2>Login</h2>
    <form action="loginPost" method="post">
        <label for="email">Email:</label>
        <input type="email" id="email" name="customer[customer_email]" required>
        <label for="password">Password:</label>
        <input type="password" id="password" name="customer[password]" required>
        <input type="submit" value="Login">
        <div class="form-links">
            <a href="http://localhost/practice/mvc/customer/account/forgot">
                Forgot Password?
            </a> | <a href="http://localhost/practice/mvc/customer/account/register">
                Register
            </a>
        </div>
    </form>
</div>