<?php
$productCollection = $this->getBanner();
?>

<div class="card radius-10">
    <div class="card-header py-3">
        <div class="row align-items-center g-3">
            <div class="col-12 col-lg-6">
                <h2 class="mb-0">Banner List</h2>
            </div>
        </div>
    </div>

    <div class="card-body">
        <div class="table-responsive mt-2">
            <table id="example" class="table align-middle mb-0 table-striped table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Image Name</th>
                        <th>Image</th>
                        <th>Status</th>
                        <th>Show-On</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($productCollection->getData() as $product): ?>
                    <tr>
                        <td>
                            <?php echo $product->getBannerId(); ?>
                        </td>
                        <td>
                            <?php echo $product->getBannerImage(); ?>
                        </td>
                        <td>
                            <img src="<?php echo $this->getImage($product->getBannerImage()); ?>" alt="Logo" id="img1">
                        </td>
                        <td>
                            <?php echo $product->mapStatus(); ?>
                        </td>
                        <td>
                            <?php echo $product->getShowOn(); ?>
                        </td>
                        <td class="text-center">
                            <a href="<?php echo Mage::getBaseUrl("admin/banner/form?id=" . $product->getBannerId()); ?>"
                                class="btn btn-warning" title="Edit info">Edit</a>
                        </td>
                        <td class="text-center">
                            <a href="<?php echo Mage::getBaseUrl("admin/banner/delete?id=" . $product->getBannerId()); ?>"
                                class="btn btn-danger" title="Delete">Delete
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="addNewButton">
    <a href="form" class="btn btn-primary me-2">
        Add New Banner
    </a>
</div><br>